import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../globals.css";

const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen p-5 bg-gray-100 font-sans">
      <div className="bg-white shadow-md rounded-lg p-4 flex justify-between items-center">
        <h2 className="font-bold text-2xl text-gray-800">나만의 레시피</h2>
      </div>
      {children}
    </div>
  );
}
 